//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::folder::Entity as Folder;
pub use super::image::Entity as Image;
pub use super::share::Entity as Share;
pub use super::user::Entity as User;
pub use super::user_image::Entity as UserImage;
